gdb: pruning more conflict
Yet another directory that conflicts.

Linking /usr/local/Cellar/binutils/2.24...
Error: Could not symlink share/info/bfd.info
Target /usr/local/share/info/bfd.info

Linking /usr/local/Cellar/binutils/2.24...
Error: Could not symlink share/info/configure.info
Target /usr/local/share/info/configure.info

Closes Homebrew/homebrew#382.

Signed-off-by: Jack Nagel <jacknagel@gmail.com>